remote_theme: pages-themes/hacker@v0.2.0
plugins: jekyll-remote-theme
title: ac1dTigR's homepage
description: This is a place where I will put down my thoughts, ideas, and solutions to niche problems that I hope will be useful to other people.
